image: node:16-alpine3.14

variables:
  CI: "use"
  TAG: registry.gmdp.io/glonassmobile/tapmobile/web

default:
  before_script:
    - mkdir -p ~/.docker/
    - cat $docker_config > ~/.docker/config.json
    - cat $npmrc > ~/.npmrc

cache:
  paths:
    - node_modules/

stages:
    - build
    - publish

build_next:
    stage: build
    script:
        - yarn
    artifacts:
        when: always
        paths:
            - build

publish_server_master:
  only:
    - main
  stage: publish
  image: docker:20.10.12
  script:
    - cd build
    - npmrc=$(cat ~/.npmrc| base64)
    - export DOCKER_TAG=$TAG/server:latest
    - docker build --build-arg NPMRC="$npmrc" -t $DOCKER_TAG .
    - docker push $DOCKER_TAG

publish_static_master:
    stage: publish
    image: docker:20.10.12
    only:
        - main
    script:
        - cd public
        - export DOCKER_TAG=$TAG/static:latest
        - docker build -t $DOCKER_TAG .
        - docker push $DOCKER_TAG
