apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}-static
          image: {{ .Values.image }}/static:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: KUBE_POD_NAME
              value: {{ .Chart.Name }}
            - name: KUBE_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
        - name: {{ .Chart.Name }}-server
          image: {{ .Values.image }}/server:{{ .Values.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: KUBE_POD_NAME
              value: { { .Chart.Name } }
            - name: KUBE_NAMESPACE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
